server:
  port: 8080
spring:
  application:
    name: npe-demo-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://182.61.46.157:39336/npe_demo_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: F5m4JExC42fbZF3b


# MyBatis配置
mybatis:
  type-aliases-package: com.npe.demo.entity
  mapper-locations: classpath:mapper/*.xml


# 搜索指定包别名
#  typeAliasesPackage: com.ruoyi.**.domain
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath*:mapper/**/*Mapper.xml
#  # 加载全局的配置文件
#  configLocation: classpath:mybatis/mybatis-config.xml


