server:
  port: 8001
spring:
  application:
    name: npe-demo-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/test01?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true

# MyBatis配置
mybatis:
  type-aliases-package: com.npe.demo.entity
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
#    是否注册 默认true
    register-with-eureka: true
#    是否集群 默认true
    fetch-registry: true
    service-url:
      defaultZone: http://Eureka7001.com:7001/eureka,http://Eureka7002.com:7002/eureka
      #这里如果不写会报错--》是个坑没有提示
#      defaultZone: http://localhost:7001/eureka
  instance:
    #修改主机名称：别名
    instance-id: payment-8001
    #显示IP地址
    prefer-ip-address: true
    #默认30秒
    lease-renewal-interval-in-seconds: 2
    #默认90秒 最后一次等待超时时间
    lease-expiration-duration-in-seconds: 30
# 搜索指定包别名
#  typeAliasesPackage: com.ruoyi.**.domain
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath*:mapper/**/*Mapper.xml
#  # 加载全局的配置文件
#  configLocation: classpath:mybatis/mybatis-config.xml


