server:
  port: 8004
spring:
  application:
    name: npe-demo-payment-8004
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/test01?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true
  cloud:
    zookeeper:
      connect-string: 182.61.46.157:2181




# MyBatis配置
mybatis:
  type-aliases-package: com.npe.demo.entity
  mapper-locations: classpath:mapper/*.xml





