server:
  port: 80
spring:
  application:
    name: npe-demo-order
eureka:
  client:
    #    是否注册 默认true
    register-with-eureka: true
    #    是否集群 默认true
    fetch-registry: true
    service-url:
      #这里如果不写会报错--》是个坑没有提示
      defaultZone: http://Eureka7001.com:7001/eureka,http://Eureka7002.com:7002/eureka
